import { action } from "./_generated/server";
import { v } from "convex/values";
import { validateString } from "./validator";
import { api } from "./_generated/api";

const CANDIDATE_MODELS = [
  "gemini-3.6-flash",
  "gemini-flash-latest",
  "gemini-3.8-flash",
  "gemini-3.5-flash",
];

export const generateResponse = action({
  args: {
    contents: v.array(
      v.object({
        role: v.string(),
        parts: v.array(
          v.object({
            text: v.string(),
          })
        ),
      })
    ),
  },
  handler: async (ctx, args) => {
    // Check authentication
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Unauthorized");
    }

    // Rate Limiting: general authenticated user action
    const limitCheck = await ctx.runMutation(api.rateLimiter.checkRateLimitMutation, {
      key: `user:${identity.subject}`,
      endpoint: "gemini.generateResponse",
      type: "authenticated",
    });
    if (!limitCheck.allowed) {
      throw new Error(limitCheck.reason);
    }

    // Validate contents array strictly
    if (!args.contents || args.contents.length === 0) {
      throw new Error("Contents array cannot be empty");
    }
    if (args.contents.length > 50) {
      throw new Error("Too many messages in history context");
    }

    for (const item of args.contents) {
      validateString(item.role, { enumValues: ["user", "model"], name: "role" });
      if (item.parts.length === 0 || item.parts.length > 5) {
        throw new Error("Invalid parts length in contents");
      }
      for (const part of item.parts) {
        validateString(part.text, { min: 1, max: 10000, name: "part text" });
      }
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("Gemini API key is not configured in the Convex dashboard");
    }

    const ATHREYA_SYSTEM_INSTRUCTION = {
      parts: [
        {
          text: "You are Athreya, the dedicated AI Learning Assistant for GuruKulX, a peer-to-peer skill-sharing and mentorship platform. When greeted or asked who you are, always introduce yourself warmly as Athreya: 'Hi! I am your AI assistant Athreya, here to help you learn, master new skills, and connect with peers on GuruKulX.' Be supportive, practical, encouraging, and focused on helping users accelerate their learning and find skill exchanges."
        }
      ]
    };

    let lastError = null;

    for (const model of CANDIDATE_MODELS) {
      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(new Error("Timeout")), 10000);

      try {
        const url = `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${apiKey}`;

        const res = await fetch(url, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify({
            systemInstruction: ATHREYA_SYSTEM_INSTRUCTION,
            contents: args.contents,
          }),
          signal: controller.signal,
        });

        clearTimeout(timeoutId);

        const data = await res.json();

        if (data?.error) {
          const errCode = data.error.code || res.status;
          const errMsg = data.error.message || "Unknown error";
          console.warn(`Gemini model ${model} returned error (${errCode}): ${errMsg}`);
          lastError = new Error(errMsg);

          // If high demand (503), rate limit (429), or temporary server error (500), try next model
          if (errCode === 503 || errCode === 429 || errCode === 500 || errMsg.toLowerCase().includes("demand")) {
            continue;
          }
          if (errCode === 400 && errMsg.toLowerCase().includes("api key")) {
            throw new Error("Invalid Gemini API key");
          }
          continue;
        }

        const responseText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!responseText) {
          console.warn(`Gemini model ${model} produced no text parts, trying next model`);
          lastError = new Error("No response content generated by Gemini API");
          continue;
        }

        return responseText;
      } catch (err) {
        clearTimeout(timeoutId);
        if (err.message === "Invalid Gemini API key") {
          throw err;
        }
        console.warn(`Gemini request to ${model} threw error: ${err.message}`);
        lastError = err;
      }
    }

    // Smart contextual fallback with Athreya persona if models face temporary high-demand spikes
    const latestUserText = [...args.contents].reverse().find(c => c.role === 'user')?.parts?.[0]?.text || '';
    if (latestUserText) {
      const lower = latestUserText.toLowerCase();
      if (lower.includes("who are you") || lower.includes("hello") || lower.includes("hi")) {
        return "Hi! I am your AI assistant Athreya, here to help you learn, master new skills, and connect with peers on GuruKulX. Whether you're looking for learning roadmaps, skill suggestions, or finding exchange partners, I'm here to guide you! What would you like to explore today?";
      }
      if (lower.includes("skill") || lower.includes("learn") || lower.includes("suggest") || lower.includes("next")) {
        return "Hi! I am your AI assistant Athreya, here to help you learn and grow! Based on popular exchanges across GuruKulX, here are high-impact skills to explore next:\n\n1. **Full-Stack Development** (React, Next.js, Node.js, Convex)\n2. **AI & Prompt Engineering** (LLM APIs, AI Agents, Prompting)\n3. **UI/UX & Product Design** (Figma, Clean Design Systems, Prototyping)\n4. **Communication & Peer Mentorship** (Pitching, Teaching, Constructive Feedback)\n\nTell me a little about your background, and I can tailor a custom learning roadmap for you!";
      }
      if (lower.includes("plan") || lower.includes("schedule") || lower.includes("7-day")) {
        return "Hi! I am your AI assistant Athreya. Here is a recommended 7-day learning roadmap:\n\n- **Days 1-2**: Learn core fundamentals and review documentation\n- **Days 3-4**: Build a mini-project or solve practical problems\n- **Day 5**: Schedule a skill exchange session with a peer on GuruKulX\n- **Days 6-7**: Refactor your work and plan the next milestones\n\nWhat specific topic or skill should we build a custom roadmap for?";
      }
    }

    throw lastError || new Error("The AI model is currently experiencing high demand across all fallbacks. Please try again shortly.");
  },
});
