import { action } from "./_generated/server";
import { v } from "convex/values";
import { validateString } from "./validator";
import { api } from "./_generated/api";

export const generateResponse = action({
  args: {
    contents: v.array(
      v.object({
        role: v.string(),
        parts: v.array(
          v.object({
            text: v.string(),
          })
        ),
      })
    ),
  },
  handler: async (ctx, args) => {
    // Check authentication
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) {
      throw new Error("Unauthorized");
    }

    // Rate Limiting: general authenticated user action
    const limitCheck = await ctx.runMutation(api.rateLimiter.checkRateLimitMutation, {
      key: `user:${identity.subject}`,
      endpoint: "gemini.generateResponse",
      type: "authenticated",
    });
    if (!limitCheck.allowed) {
      throw new Error(limitCheck.reason);
    }

    // Validate contents array strictly
    if (args.contents.length === 0) {
      throw new Error("Contents array cannot be empty");
    }
    if (args.contents.length > 50) {
      throw new Error("Too many messages in history context");
    }

    for (const item of args.contents) {
      validateString(item.role, { enumValues: ["user", "model"], name: "role" });
      if (item.parts.length === 0 || item.parts.length > 5) {
        throw new Error("Invalid parts length in contents");
      }
      for (const part of item.parts) {
        validateString(part.text, { min: 1, max: 10000, name: "part text" });
      }
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      throw new Error("Gemini API key is not configured in the Convex dashboard");
    }

    const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=${apiKey}`;

    const res = await fetch(url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ contents: args.contents }),
    });

    const data = await res.json();
    if (data?.error) {
      console.error("Gemini API Error:", JSON.stringify(data, null, 2));
      throw new Error(data.error.message || "Gemini API error");
    }

    const responseText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!responseText) {
      throw new Error("No response content generated by Gemini API");
    }

    return responseText;
  },
});
